//Create a user
POST http://localhost:3000/login
Content-Type: application/json

{
    "name" : "fli",
    "email" : "fli@gmail.com",
    "password" : "fli123",
    "confirmPassword" : "fli123",
    "role" : "admin"
}